### ISSUE TITLE
Move log out button to Profile page

### ISSUE THREAD

**Issue by hundredball** [CalCOFI/OceanView#18]
For me, it makes more sense to put a log-out button on the Profile page since it is related to account activity. Please let me know if it makes sense to you or not.

**Comment by mfrants** [comment]
Yes, I think that’s a good idea.

Marina Frants (she/her/hers)
Information Manager, CCE-LTER/CalCOFI
Scripps Institution of Oceanography, La Jolla, CA
***@***.***

**Comment by hundredball** [comment]
Sounds good! I feel that we can start improving these issues after the current PR is merged so we can test on the iOS platform.
