### ISSUE TITLE
Photo library doesn't work as expected

### ISSUE THREAD

**Issue by hundredball** [CalCOFI/OceanView#22]
## Reproduce step
- Use photo library
- Sometimes multiple photos can be selected
- After choosing one photo and go into observation page, press back button and leave without saving
- Use photo library and select any photo 
- The page will be navigated to upload page instead of observation page

## Expected
- Only one photo can be selected in photo library
- After selecting one photo, the page should be directed to observation page every time

**Comment by mfrants** [comment]
Hi Chieh

I’ve assigned bug #22 to myself.

Marina Frants (she/her/hers)
Information Manager, CCE-LTER/CalCOFI
Scripps Institution of Oceanography, La Jolla, CA
***@***.***

**Comment by hundredball** [comment]
Hi Marina, I fixed the bug for location and it works on iOS device now. You can proceed your fix on the main branch. 

In terms of testing on iOS device, you can set up environment according to following picture and simply run and deploy the app to your device when it's physically connected to your Mac. Please let me know if you still have problem setting it up. 
<img width="1440" alt="Screen Shot 2023-03-22 at 11 31 16 PM" src="https://user-images.githubusercontent.com/21293342/227122195-63bf9f05-d8a0-44ee-89
<img width="749" alt="Screen Shot 2023-03-13 at 10 02 58 AM" src="https://user-images.githubusercontent.com/21293342/227122217-5ae6fd16-ce69-4ca6-825b-bc59a793ddf8.png">
76-4ce4a32013dc.png">
<img width="1440" alt="Screen Shot 2023-03-22 at 11 31 04 PM" src="https://user-images.githubusercontent.com/21293342/227122204-1a9bd3de-f03d-43c3-ae43-480eb5e3ade3.png">

**Comment by hundredball** [comment]
Nice catch Marina! Yes, it's a good idea we set the time limit for searching. I think it would be great to also set time limit for text search as well.

**Comment by mfrants** [comment]
Hi Chieh.

I committed a change in extract_exif.dart that I think fixes the photo
library bug.  At least, I can't make it happen anymore, when before I could
make it happen easily.  Git was giving me a bunch of errors when I tried to
check out main, so to speed things up I just made the change directly in
github and committed it.  It was just a small one-line thing, so hopefully
that's okay.

Marina Frants
Information Manager, CCE-LTER and CalCOFI
Scripps Institution of Oceanography
***@***.***

**Comment by hundredball** [comment]
Hi Marina, 

Thanks for identifying this issue. As I tested, it also fixes another issue the metadata wasn't successfully loaded on my device. 

I think the reason why you got lots of errors when checkout to main might be due to the commit conflict. We can briefly discuss it in the meeting tomorrow in case it happened again. Thanks for fixing this issue though! It works well so far :)
